'use strict';

const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const usersRoutes = require('./users.routes');
const studentsRoutes = require('./students.routes');
const teachersRoutes = require('./teachers.routes');
const subjectsRoutes = require('./subjects.routes');
const branchesRoutes = require('./branches.routes');
const academicYearsRoutes = require('./academicYears.routes');
const academicPeriodsRoutes = require('./academicPeriods.routes');
const academicHistoryRoutes = require('./academicHistory.routes');
const assignmentsRoutes = require('./assignments.routes');
const attendanceRoutes = require('./attendance.routes');
const gradesRoutes = require('./grades.routes');
const gradeChangeRequestsRoutes = require('./gradeChangeRequests.routes');
const gpaRoutes = require('./gpa.routes');
const creditsRoutes = require('./credits.routes');
const scholarshipsRoutes = require('./scholarships.routes');
const guardiansRoutes = require('./guardians.routes');
const medicalRecordsRoutes = require('./medicalRecords.routes');
const previousSchoolsRoutes = require('./previousSchools.routes');
const documentsRoutes = require('./documents.routes');
const calendarRoutes = require('./calendar.routes');
const graduationRoutes = require('./graduation.routes');
const gransifRoutes = require('./gransif.routes');
const progressReportsRoutes = require('./progressReports.routes');
const reportCardsRoutes = require('./reportCards.routes');
const transcriptsRoutes = require('./transcripts.routes');
const reportsRoutes = require('./reports.routes');
const auditRoutes = require('./audit.routes');
const activityRoutes = require('./activity.routes');
const rolesRoutes = require('./roles.routes');
const permissionsRoutes = require('./permissions.routes');
const settingsRoutes = require('./settings.routes');
const systemRoutes = require('./system.routes');

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/students', studentsRoutes);
router.use('/teachers', teachersRoutes);
router.use('/subjects', subjectsRoutes);
router.use('/branches', branchesRoutes);
router.use('/academic-years', academicYearsRoutes);
router.use('/academic-periods', academicPeriodsRoutes);
router.use('/academic-history', academicHistoryRoutes);
router.use('/assignments', assignmentsRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/grades', gradesRoutes);
router.use('/grade-change-requests', gradeChangeRequestsRoutes);
router.use('/gpa', gpaRoutes);
router.use('/credits', creditsRoutes);
router.use('/scholarships', scholarshipsRoutes);
router.use('/guardians', guardiansRoutes);
router.use('/medical-records', medicalRecordsRoutes);
router.use('/previous-schools', previousSchoolsRoutes);
router.use('/documents', documentsRoutes);
router.use('/calendar', calendarRoutes);
router.use('/graduation', graduationRoutes);
router.use('/gransif', gransifRoutes);
router.use('/progress-reports', progressReportsRoutes);
router.use('/report-cards', reportCardsRoutes);
router.use('/transcripts', transcriptsRoutes);
router.use('/reports', reportsRoutes);
router.use('/audit', auditRoutes);
router.use('/activity', activityRoutes);
router.use('/roles', rolesRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/settings', settingsRoutes);
router.use('/system', systemRoutes);

module.exports = router;
